---
title: "P8108_final_project_p3"
author: "Zihan Wu"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE, waring = F}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(tidyverse)
library(car)
library(MASS)
heart_failure_data <- read_csv("C:/Users/Lenovo/Downloads/heart_failure_clinical_records_dataset.csv")
```

```{r}
heart_failure_data$high_blood_pressure <- as.factor(heart_failure_data$high_blood_pressure)
heart_failure_data$anaemia <- as.factor(heart_failure_data$anaemia)
heart_failure_data$diabetes <- as.factor(heart_failure_data$diabetes)
heart_failure_data$sex <- as.factor(heart_failure_data$sex)

heart_failure_data <- heart_failure_data %>%
  mutate(
    log_cp = log(creatinine_phosphokinase),
    log_serum_creatinine = log(serum_creatinine)
  )
```

### Cox

```{r}
# transform non-linear

# initial model with transformed and linear variables
# select covariates with alpha = 0.2
coxph(
  Surv(time, DEATH_EVENT) ~ age,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ log_cp,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ ejection_fraction,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ platelets,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ anaemia,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ log_serum_creatinine,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ serum_sodium,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ diabetes,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ high_blood_pressure,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ sex,
  data = heart_failure_data
)

coxph(
  Surv(time, DEATH_EVENT) ~ smoking,
  data = heart_failure_data
)

# age ejection_fraction anaemia log_serum_creatinine serum_sodium high_blood_pressure
```

```{r}

# Define the Cox proportional hazards model
cox_full <- coxph(
  Surv(time, DEATH_EVENT) ~ age + ejection_fraction + log_serum_creatinine + serum_sodium + anaemia + high_blood_pressure,
  data = heart_failure_data
)

cox_backward <- step(cox_full, direction = "backward")
# out:serum_sodium
summary(cox_backward)
```

```{r}
#forward stepwise
cox_null <- coxph(Surv(time, DEATH_EVENT) ~ 1, data = heart_failure_data)
cox_forward <- step(cox_null, 
                   scope = ~ age + log_cp + ejection_fraction + 
                     platelets + log_serum_creatinine + serum_sodium +
                     anaemia + diabetes + high_blood_pressure + sex + smoking,
                   direction = "forward")
summary(cox_forward)
```

```{r}
# interactions

cox_interaction <- coxph(
  Surv(time, DEATH_EVENT) ~ age +
    high_blood_pressure +
    anaemia +
    ejection_fraction +
    log_serum_creatinine +
    age * high_blood_pressure +
    age * anaemia +
    age * ejection_fraction +
    age * log_serum_creatinine +
    high_blood_pressure * anaemia +
    high_blood_pressure * ejection_fraction +
    high_blood_pressure * log_serum_creatinine +
    anaemia * ejection_fraction +
    anaemia * log_serum_creatinine +
    ejection_fraction * log_serum_creatinine,
  data = heart_failure_data
)

cox_int <- stepAIC(
  cox_interaction, 
  direction = "both", 
  trace = TRUE
)

summary(cox_int)
```

```{r}
aic_comparison <- AIC(cox_full, cox_backward, cox_forward, cox_int)
print(aic_comparison)

# VIF test for final selected variables
vif(lm(time ~ age + ejection_fraction + log_serum_creatinine + 
       anaemia + high_blood_pressure + age*ejection_fraction + ejection_fraction*log_serum_creatinine,
       data = heart_failure_data),type = 'predictor')
```
All VIF values are close to 1 (range: 1.01-1.08)
No multicollinearity issues
age ejection_fraction log_serum_creatinine anaemia high_blood_pressure

### AFT
```{r}
survreg(
  Surv(time, DEATH_EVENT) ~ age,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_cp,
  dist = "weibull",
  data = heart_failure_data
)


survreg(
  Surv(time, DEATH_EVENT) ~ ejection_fraction,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ platelets,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_serum_creatinine,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ serum_sodium,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ anaemia,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ diabetes,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ high_blood_pressure,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ sex,
  dist = "weibull",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ smoking,
  dist = "weibull",
  data = heart_failure_data
)
 
# high_blood_pressure anaemia serum_sodium log_serum_creatinine ejection_fraction age
```

```{r}
weibull_full <- 
survreg(
  Surv(time, DEATH_EVENT) ~ age + ejection_fraction + log_serum_creatinine + serum_sodium + anaemia + high_blood_pressure,
  dist = "weibull",
  data = heart_failure_data
)

weib_backward <- step(weibull_full, direction = "backward")
summary(weib_backward)
# out:serum_sodium
```

```{r}
#forward stepwise
weibull_null <- survreg(Surv(time, DEATH_EVENT) ~ 1, dist = "weibull", data = heart_failure_data)
weib_forward <- step(weibull_null, 
                   scope = ~ age + log_cp + ejection_fraction + 
                     platelets + log_serum_creatinine + serum_sodium +
                     anaemia + diabetes + high_blood_pressure + sex + smoking,
,data = heart_failure_data,
                   direction = "forward")

summary(weib_forward)
```

```{r}
weib_interaction <- survreg(
  Surv(time, DEATH_EVENT) ~ age +
    high_blood_pressure +
    anaemia +
    ejection_fraction +
    log_serum_creatinine +
    age * high_blood_pressure +
    age * anaemia +
    age * ejection_fraction +
    age * log_serum_creatinine +
    high_blood_pressure * anaemia +
    high_blood_pressure * ejection_fraction +
    high_blood_pressure * log_serum_creatinine +
    anaemia * ejection_fraction +
    anaemia * log_serum_creatinine +
    ejection_fraction * log_serum_creatinine,
  dist = "weibull",
  data = heart_failure_data
)
weib_int <- stepAIC(weib_interaction, direction = "both")
summary(weib_int)
```

```{r}
survreg(
  Surv(time, DEATH_EVENT) ~ age,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_cp,
  dist = "exponential",
  data = heart_failure_data
)


survreg(
  Surv(time, DEATH_EVENT) ~ ejection_fraction,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ platelets,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_serum_creatinine,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ serum_sodium,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ anaemia,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ diabetes,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ high_blood_pressure,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ sex,
  dist = "exponential",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ smoking,
  dist = "exponential",
  data = heart_failure_data
)
 
# high_blood_pressure anaemia serum_sodium log_serum_creatinine ejection_fraction age
```

```{r}
exponential_full <- 
survreg(
  Surv(time, DEATH_EVENT) ~ age + ejection_fraction + log_serum_creatinine + serum_sodium + anaemia + high_blood_pressure,
  dist = "exponential",
  data = heart_failure_data
)

exp_backward <- step(exponential_full, direction = "backward")
summary(exp_backward)
# out:serum_sodium
```

```{r}
#forward stepwise
exponential_null <- survreg(Surv(time, DEATH_EVENT) ~ 1, dist = "exponential", data = heart_failure_data)
exp_forward <- step(exponential_null, 
                   scope = ~ age + log_cp + ejection_fraction + 
                     platelets + log_serum_creatinine + serum_sodium +
                     anaemia + diabetes + high_blood_pressure + sex + smoking,
,data = heart_failure_data,
                   direction = "forward")

summary(exp_forward)
```

```{r}
exp_interaction <- survreg(
  Surv(time, DEATH_EVENT) ~ age +
    high_blood_pressure +
    anaemia +
    ejection_fraction +
    log_serum_creatinine +
    age * high_blood_pressure +
    age * anaemia +
    age * ejection_fraction +
    age * log_serum_creatinine +
    high_blood_pressure * anaemia +
    high_blood_pressure * ejection_fraction +
    high_blood_pressure * log_serum_creatinine +
    anaemia * ejection_fraction +
    anaemia * log_serum_creatinine +
    ejection_fraction * log_serum_creatinine,
  dist = "exponential",
  data = heart_failure_data
)
exp_int <- stepAIC(exp_interaction, direction = "both")
summary(exp_int)
```

All the same covariates.

```{r}
aic_cox <- AIC(cox_full, cox_backward, cox_forward, cox_int)
print(aic_cox)

aic_weib <- AIC(weibull_full,weib_forward, weib_backward, weib_int)
print(aic_weib)

aic_exp <- AIC(exponential_full, exp_forward, exp_backward, exp_int)
print(aic_exp)
```

```{r}
AIC(exp_int,cox_int,weib_int)
```


```{r}
survreg(
  Surv(time, DEATH_EVENT) ~ age,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_cp,
  dist = "loglogistic",
  data = heart_failure_data
)


survreg(
  Surv(time, DEATH_EVENT) ~ ejection_fraction,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ platelets,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_serum_creatinine,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ serum_sodium,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ anaemia,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ diabetes,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ high_blood_pressure,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ sex,
  dist = "loglogistic",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ smoking,
  dist = "loglogistic",
  data = heart_failure_data
)
 
# high_blood_pressure anaemia serum_sodium log_serum_creatinine ejection_fraction age
```

```{r}
loglogistic_full <- 
survreg(
  Surv(time, DEATH_EVENT) ~ age + ejection_fraction + log_serum_creatinine + serum_sodium + anaemia + high_blood_pressure,
  dist = "loglogistic",
  data = heart_failure_data
)

llog_backward <- step(loglogistic_full, direction = "backward")
summary(llog_backward)
# out:serum_sodium
```

```{r}
#forward stepwise
loglogistic_null <- survreg(Surv(time, DEATH_EVENT) ~ 1, dist = "loglogistic", data = heart_failure_data)
llog_forward <- step(loglogistic_null, 
                   scope = ~ age + log_cp + ejection_fraction + 
                     platelets + log_serum_creatinine + serum_sodium +
                     anaemia + diabetes + high_blood_pressure + sex + smoking,
,data = heart_failure_data,
                   direction = "forward")

summary(llog_forward)
```

```{r}
llog_interaction <- survreg(
  Surv(time, DEATH_EVENT) ~ age +
    high_blood_pressure +
    anaemia +
    ejection_fraction +
    log_serum_creatinine +
    age * high_blood_pressure +
    age * anaemia +
    age * ejection_fraction +
    age * log_serum_creatinine +
    high_blood_pressure * anaemia +
    high_blood_pressure * ejection_fraction +
    high_blood_pressure * log_serum_creatinine +
    anaemia * ejection_fraction +
    anaemia * log_serum_creatinine +
    ejection_fraction * log_serum_creatinine,
  dist = "loglogistic",
  data = heart_failure_data
)
llog_int <- stepAIC(llog_interaction, direction = "both")
summary(llog_int)
```


```{r}
survreg(
  Surv(time, DEATH_EVENT) ~ age,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_cp,
  dist = "lognormal",
  data = heart_failure_data
)


survreg(
  Surv(time, DEATH_EVENT) ~ ejection_fraction,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ platelets,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ log_serum_creatinine,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ serum_sodium,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ anaemia,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ diabetes,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ high_blood_pressure,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ sex,
  dist = "lognormal",
  data = heart_failure_data
)

survreg(
  Surv(time, DEATH_EVENT) ~ smoking,
  dist = "lognormal",
  data = heart_failure_data
)
 
# high_blood_pressure anaemia serum_sodium log_serum_creatinine ejection_fraction age
```

```{r}
lognormal_full <- 
survreg(
  Surv(time, DEATH_EVENT) ~ age + ejection_fraction + log_serum_creatinine + serum_sodium + anaemia + high_blood_pressure,
  dist = "lognormal",
  data = heart_failure_data
)

logn_backward <- step(lognormal_full, direction = "backward")
summary(logn_backward)
```

```{r}
#forward stepwise
lognormal_null <- survreg(Surv(time, DEATH_EVENT) ~ 1, dist = "lognormal", data = heart_failure_data)
logn_forward <- step(lognormal_null, 
                   scope = ~ age + log_cp + ejection_fraction + 
                     platelets + log_serum_creatinine + serum_sodium +
                     anaemia + diabetes + high_blood_pressure + sex + smoking,
,data = heart_failure_data,
                   direction = "forward")

summary(logn_forward)
```

```{r}
logn_interaction <- survreg(
  Surv(time, DEATH_EVENT) ~ age +
    high_blood_pressure +
    anaemia +
    ejection_fraction +
    log_serum_creatinine +
    serum_sodium+
    age*serum_sodium+
    serum_sodium*high_blood_pressure+
    serum_sodium*anaemia +
    serum_sodium*ejection_fraction +
    serum_sodium*log_serum_creatinine +
    age * high_blood_pressure +
    age * anaemia +
    age * ejection_fraction +
    age * log_serum_creatinine +
    high_blood_pressure * anaemia +
    high_blood_pressure * ejection_fraction +
    high_blood_pressure * log_serum_creatinine +
    anaemia * ejection_fraction +
    anaemia * log_serum_creatinine +
    ejection_fraction * log_serum_creatinine,
  dist = "lognormal",
  data = heart_failure_data
)
logn_int <- stepAIC(logn_interaction, direction = "both")
summary(logn_int)
```

```{r}
AIC(exp_int,llog_int,logn_int,cox_int,weib_int)
```


```{r}
surv_obj <- Surv(heart_failure_data$time, heart_failure_data$DEATH_EVENT)
fit_total <- survfit(surv_obj ~ 1, data = heart_failure_data)

g_total <- ggsurvplot(
  fit_total, 
  data = heart_failure_data, 
  conf.int = FALSE,
  xlab = "Time", 
  ylab = "Cumulative Hazard", 
  ggtheme = theme_minimal(),
  risk.table = FALSE, 
  fun = "cumhaz", 
  main = "Cumulative Hazard (Total)",
  palette = "black"  
)

print(g_total)

```

```{r}

# 获取模型摘要
summary_cox <- summary(cox_int)

# 提取需要的信息
coefs <- summary_cox$coefficients[, "coef"]
p_values <- summary_cox$coefficients[, "Pr(>|z|)"]
exp_coefs <- (summary_cox$conf.int[, "exp(coef)"])
lower95 <- (summary_cox$conf.int[, "lower .95"])
upper95 <- (summary_cox$conf.int[, "upper .95"])

# 创建数据框
df <- data.frame(
  Coef = coefs,
  P_Value = p_values,
  Exp_Coef = exp_coefs,
  Lower_95_CI = lower95,
  Upper_95_CI = upper95
)

# 查看DataFrame
print(df)

```

```{r}
exp_summary=summary(exp_int)
coefficients_vector <- exp_summary$coefficients
exp_summary$var
exp_df <- data.frame(
  Value = -coefficients_vector,
  SD = sqrt(diag(exp_summary$var)),
  P = exp_summary[["table"]][, "p"],
  stringsAsFactors = FALSE  
)
exp_df <- exp_df |>
  mutate(
    CI_Lower = Value - 1.96 * SD,                  
    CI_Upper = Value + 1.96 * SD,                 
    Exp_Value = exp(Value),                        
    Exp_CI_Lower = exp(CI_Lower),                
    Exp_CI_Upper = exp(CI_Upper)                  
  )

```